#!/bin/sh
# Writes .env for a local VeriSettle stack.
#
# The variable layout below IS the template - there is no .env.example in
# this repo, deliberately: a checked-in env file is the single most common
# way real credentials reach a public repo by accident, and a template that
# only ever holds placeholders still has to be kept in sync by hand. One
# script that emits the file removes both problems.
#
# Every __RAND_HEX_n__ below is replaced with a fresh `openssl rand -hex n`.
# The widths are not arbitrary - see docs/secrets-reference.md for why each
# value is 8, 12, 16 or 32 bytes.
#
# Refuses to overwrite an existing .env: once the stack has run, those
# secrets are baked into the Postgres, MinIO, Keycloak and Langfuse
# volumes, and regenerating them locks you out of your own data. To start
# genuinely fresh: make clean, then FORCE=1 make env.
#
# Run from the repo root: sh infra/scripts/generate-env.sh
set -eu

cd "$(dirname "$0")/../.."

if [ -f .env ] && [ "${FORCE:-0}" != "1" ]; then
  echo ".env already exists - refusing to overwrite it." >&2
  echo "Its secrets are baked into your Docker volumes; replacing them would" >&2
  echo "break the stack. To regenerate anyway: make clean && FORCE=1 make env" >&2
  exit 1
fi

TMPL=$(mktemp); OUT=$(mktemp)
trap 'rm -f "$TMPL" "$OUT"' EXIT

cat > "$TMPL" <<'EOT'
# VeriSettle - local development environment.
#
# Generated by infra/scripts/generate-env.sh (make env). Never commit this
# file: it is gitignored, and it holds this machine's real credentials.
#
# Values marked [AUTO-FILLED] are written later by a setup script - the
# README says which one, at the step that produces them. Leave them blank.

# ----------------------------------------------------------------------
# 1. YOU MUST FILL THESE IN - the only two real external keys
# ----------------------------------------------------------------------
OPENAI_API_KEY=sk-replace-me
GROQ_API_KEY=gsk-replace-me

# ----------------------------------------------------------------------
# 2. Compose / base
# ----------------------------------------------------------------------
COMPOSE_PROJECT_NAME=verisettle
POSTGRES_SUPERUSER=postgres
POSTGRES_SUPERUSER_PASSWORD=__RAND_HEX_16__

PGPASS_KEYCLOAK=__RAND_HEX_16__
PGPASS_INFISICAL=__RAND_HEX_16__
PGPASS_LITELLM=__RAND_HEX_16__
PGPASS_MLFLOW=__RAND_HEX_16__
PGPASS_LANGFUSE=__RAND_HEX_16__
PGPASS_VERISETTLE_LEDGER=__RAND_HEX_16__
PGPASS_VERISETTLE_BACKEND=__RAND_HEX_16__

# MinIO root account
MINIO_ROOT_USER=verisettle_admin___RAND_HEX_4__
MINIO_ROOT_PASSWORD=__RAND_HEX_16__

# ----------------------------------------------------------------------
# 3. Identity governance
# ----------------------------------------------------------------------
# Keycloak admin console
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=__RAND_HEX_16__
KEYCLOAK_BACKEND_CLIENT_SECRET=__RAND_HEX_16__
KEYCLOAK_CONSOLE_CLIENT_SECRET=__RAND_HEX_16__

# Demo users seeded into the realm (ap.clerk.demo / controller.demo / cfo.demo)
DEMO_AP_CLERK_PASSWORD=__RAND_HEX_8__
DEMO_CONTROLLER_PASSWORD=__RAND_HEX_8__
DEMO_CFO_PASSWORD=__RAND_HEX_8__

# SPIRE
SPIRE_TRUST_DOMAIN=verisettle.local
# [AUTO-FILLED] by infra/scripts/setup-spire.sh
SPIRE_AGENT_JOIN_TOKEN=

# Infisical
INFISICAL_ADMIN_EMAIL=admin@verisettle.local
INFISICAL_ADMIN_PASSWORD=__RAND_HEX_12__
INFISICAL_ADMIN_ORGANIZATION=VeriSettle
INFISICAL_ENCRYPTION_KEY=__RAND_HEX_16__
INFISICAL_AUTH_SECRET=__RAND_HEX_16__
# [AUTO-FILLED] by infra/scripts/bootstrap-infisical.sh
INFISICAL_ORG_ID=
# [AUTO-FILLED] by infra/scripts/provision-infisical-identities.py
INFISICAL_PROJECT_ID=
# [AUTO-FILLED] by infra/scripts/provision-infisical-identities.py
PAYMENT_EXECUTION_CLIENT_ID=
# [AUTO-FILLED] by infra/scripts/provision-infisical-identities.py
PAYMENT_EXECUTION_CLIENT_SECRET=

# ----------------------------------------------------------------------
# 4. Data governance
# ----------------------------------------------------------------------
OM_POSTGRES_ROOT_PASSWORD=__RAND_HEX_16__
AIRFLOW_ADMIN_PASSWORD=__RAND_HEX_12__
USASPENDING_AGENCY="Department of Health and Human Services"
USASPENDING_FISCAL_YEAR=2024

# ----------------------------------------------------------------------
# 5. Model governance
# ----------------------------------------------------------------------
LITELLM_MASTER_KEY=sk-verisettle-master-__RAND_HEX_16__
# [AUTO-FILLED] by infra/scripts/provision-litellm-keys.py
LITELLM_KEY_AGENT_EXTRACTION=
# [AUTO-FILLED] by infra/scripts/provision-litellm-keys.py
LITELLM_KEY_AGENT_RISK_SCORING=
# [AUTO-FILLED] by infra/scripts/provision-litellm-keys.py
LITELLM_KEY_AGENT_APPROVAL=
# [AUTO-FILLED] by infra/scripts/provision-litellm-keys.py
LITELLM_KEY_AGENT_PAYMENT_EXECUTION=
# [AUTO-FILLED] by infra/scripts/provision-litellm-keys.py (falls back to LITELLM_MASTER_KEY)
LITELLM_EXTRACTION_KEY=

# ----------------------------------------------------------------------
# 6. Application services
# ----------------------------------------------------------------------
LEDGER_API_KEY=ldg-__RAND_HEX_16__
VENDOR_LOOKUP_API_KEY=vlk-__RAND_HEX_16__
SETTLEMENT_HOLD_SECONDS=20
CONSOLE_NEXTAUTH_SECRET=__RAND_HEX_32__

# ----------------------------------------------------------------------
# 7. Operations / observability
# ----------------------------------------------------------------------
LANGFUSE_SALT=__RAND_HEX_32__
LANGFUSE_ENCRYPTION_KEY=__RAND_HEX_32__
LANGFUSE_NEXTAUTH_SECRET=__RAND_HEX_32__
LANGFUSE_CLICKHOUSE_PASSWORD=__RAND_HEX_16__
LANGFUSE_REDIS_AUTH=__RAND_HEX_16__
LANGFUSE_INIT_USER_PASSWORD=__RAND_HEX_12__
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=pk-lf-__RAND_HEX_16__
LANGFUSE_INIT_PROJECT_SECRET_KEY=sk-lf-__RAND_HEX_16__

# Grafana admin
GRAFANA_ADMIN_PASSWORD=__RAND_HEX_12__
EOT

while IFS= read -r line || [ -n "$line" ]; do
  # One placeholder at a time, so two of the same width never collapse
  # into the same value.
  while printf '%s' "$line" | grep -q '__RAND_HEX_[0-9]\{1,\}__'; do
    n=$(printf '%s' "$line" | sed -n 's/.*__RAND_HEX_\([0-9]\{1,\}\)__.*/\1/p')
    v=$(openssl rand -hex "$n")
    line=$(printf '%s' "$line" | sed "s/__RAND_HEX_${n}__/${v}/")
  done
  printf '%s\n' "$line"
done < "$TMPL" > "$OUT"

mv "$OUT" .env
trap 'rm -f "$TMPL"' EXIT
chmod 600 .env

echo "wrote .env with freshly generated local secrets."
echo "Now open .env and set the two real provider keys:"
echo "  OPENAI_API_KEY=sk-..."
echo "  GROQ_API_KEY=gsk_..."
